# ============================================================================
# DevOps Platform - ArgoCD Projects (DigitalOcean)
# Ambientes: develop, qa, staging, prod
# ============================================================================
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: devops-develop
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: DevOps Platform - Ambiente de Development
  sourceRepos:
    - "https://github.com/geraldobl58/devops.git"
  destinations:
    - namespace: devops-develop
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: devops-qa
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: DevOps Platform - Ambiente de QA
  sourceRepos:
    - "https://github.com/geraldobl58/devops.git"
  destinations:
    - namespace: devops-qa
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: devops-staging
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: DevOps Platform - Ambiente de Staging
  sourceRepos:
    - "https://github.com/geraldobl58/devops.git"
  destinations:
    - namespace: devops-staging
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
---
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: devops-prod
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  description: DevOps Platform - Ambiente de Producao
  sourceRepos:
    - "https://github.com/geraldobl58/devops.git"
  destinations:
    - namespace: devops-prod
      server: https://kubernetes.default.svc
  clusterResourceWhitelist:
    - group: ""
      kind: Namespace
