# Values for Development environment
replicaCount: 1

image:
  repository: ghcr.io/geraldobl58/crivo-fe
  tag: "develop-3f6ff070d963178ebc4d95527f97e852ea83f3a4"
  pullPolicy: Always

imagePullSecrets:
  - name: ghcr-secret

ingress:
  enabled: true
  className: "nginx"
  annotations:
  hosts:
    - host: develop.fe.crivo.local
      paths:
        - path: /
          pathType: Prefix

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 10m
    memory: 64Mi

autoscaling:
  enabled: false

env:
  - name: NODE_ENV
    value: "development"
  - name: BETTER_AUTH_SECRET
    value: "crivo-super-secret-key-for-better-auth"
  - name: BETTER_AUTH_URL
    value: "http://develop.fe.crivo.local"

  - name: API_URL
    value: "http://develop.be.crivo.local"
  - name: NEXT_PUBLIC_API_URL
    value: "http://develop.be.crivo.local"
  - name: NEXT_PUBLIC_KEYCLOAK_URL
    value: "http://develop.auth.crivo.local"
  - name: NEXT_PUBLIC_KEYCLOAK_REALM
    value: "crivo"
  - name: NEXT_PUBLIC_KEYCLOAK_CLIENT_ID
    value: "crivo-web"

hostAliases:
  - ip: "10.43.45.3"
    hostnames:
      - develop.auth.crivo.local
      - develop.be.crivo.local
      - develop.fe.crivo.local

podDisruptionBudget:
  enabled: false

podAnnotations:
  app.kubernetes.io/commit: "3f6ff07"

metrics:
  enabled: false
  path: /api/metrics
  serviceMonitor:
    enabled: false
