# Values for Development environment
replicaCount: 1

image:
  repository: ghcr.io/geraldobl58/crivo-fe
  tag: "develop-3f6ff070d963178ebc4d95527f97e852ea83f3a4"
  pullPolicy: Always

imagePullSecrets:
  - name: ghcr-secret

ingress:
  enabled: true
  className: "nginx"
  annotations:
  hosts:
    - host: develop-fe.devops.local
      paths:
        - path: /
          pathType: Prefix

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 10m
    memory: 64Mi

autoscaling:
  enabled: false

env:
  NODE_ENV: development
  API_URL: http://crivo-be-develop:3000
  NEXT_PUBLIC_API_URL: http://develop-be.devops.local
  NEXT_PUBLIC_KEYCLOAK_URL: http://develop-auth.devops.local
  NEXT_PUBLIC_KEYCLOAK_REALM: devops
  NEXT_PUBLIC_KEYCLOAK_CLIENT_ID: devops-web

podDisruptionBudget:
  enabled: false

podAnnotations:
  app.kubernetes.io/commit: "3f6ff07"

metrics:
  enabled: false
  path: /api/metrics
  serviceMonitor:
    enabled: false
