# Values for Staging environment
replicaCount: 1

image:
  repository: ghcr.io/geraldobl58/crivo-fe
  tag: "develop"
  pullPolicy: Always

imagePullSecrets:
  - name: ghcr-secret

ingress:
  enabled: true
  className: "nginx"
  annotations:
  hosts:
    - host: staging.fe.crivo.local
      paths:
        - path: /
          pathType: Prefix

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 10m
    memory: 64Mi

autoscaling:
  enabled: false

env:
  - name: NODE_ENV
    value: "production"
  - name: BETTER_AUTH_SECRET
    value: "crivo-super-secret-key-for-better-auth"
  - name: BETTER_AUTH_URL
    value: "http://main.fe.crivo.local"

  - name: API_URL
    value: "http://crivo-be-staging:3000"
  - name: NEXT_PUBLIC_API_URL
    value: "http://staging.be.crivo.local"
  - name: NEXT_PUBLIC_KEYCLOAK_URL
    value: "http://staging.auth.crivo.local"
  - name: NEXT_PUBLIC_KEYCLOAK_REALM
    value: "devops"
  - name: NEXT_PUBLIC_KEYCLOAK_CLIENT_ID
    value: "devops-web"

podDisruptionBudget:
  enabled: false

podAnnotations:
  app.kubernetes.io/commit: "pending"

metrics:
  enabled: false
  path: /api/metrics
  serviceMonitor:
    enabled: false
