# Values for Staging environment
replicaCount: 1

image:
  repository: ghcr.io/geraldobl58/crivo-fe
  tag: "develop"
  pullPolicy: Always

imagePullSecrets:
  - name: ghcr-secret

ingress:
  enabled: true
  className: "nginx"
  annotations:
  hosts:
    - host: staging.fe.crivo.local
      paths:
        - path: /
          pathType: Prefix

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 10m
    memory: 64Mi

autoscaling:
  enabled: false

env:
  NODE_ENV: production
  BETTER_AUTH_SECRET: "crivo-super-secret-key-for-better-auth"
  BETTER_AUTH_URL: "http://main.fe.crivo.local"

  API_URL: http://crivo-be-staging:3000
  NEXT_PUBLIC_API_URL: http://staging.be.crivo.local
  NEXT_PUBLIC_KEYCLOAK_URL: http://staging.auth.crivo.local
  NEXT_PUBLIC_KEYCLOAK_REALM: devops
  NEXT_PUBLIC_KEYCLOAK_CLIENT_ID: devops-web

podDisruptionBudget:
  enabled: false

podAnnotations:
  app.kubernetes.io/commit: "pending"

metrics:
  enabled: false
  path: /api/metrics
  serviceMonitor:
    enabled: false
