app:
  environment: prod

ingress:
  host: prod.auth.crivo.local

env:
  KC_HOSTNAME_URL: http://prod.auth.crivo.local
  KC_HOSTNAME_ADMIN_URL: http://prod.auth.crivo.local

podDisruptionBudget:
  enabled: true
  minAvailable: 1

hostAliases:
  - ip: "10.43.45.3"
    hostnames:
      - prod.auth.crivo.local
      - prod.be.crivo.local
      - prod.fe.crivo.local
