app:
  environment: prod

image:
  # NOTA: usando tag 'develop' enquanto CI não publica tag 'main'.
  # Em prod-prod real: usar versão semântica (v1.2.3) ou SHA.
  tag: develop

ingress:
  host: prod.be.crivo.local

env:
  NODE_ENV: production
  LOG_LEVEL: warn
  SWAGGER_ENABLED: "false"
  METRICS_ENABLED: "true"
  FRONTEND_URL: http://prod.fe.crivo.local
  KEYCLOAK_BASE_URL: http://prod.auth.crivo.local
  KEYCLOAK_INTERNAL_URL: http://crivo-auth.crivo-prod.svc.cluster.local:8080
  KEYCLOAK_ISSUER: http://prod.auth.crivo.local/realms/crivo
  KEYCLOAK_JWKS_URI: http://prod.auth.crivo.local/realms/crivo/protocol/openid-connect/certs

podDisruptionBudget:
  enabled: true
  minAvailable: 1

hostAliases:
  - ip: "10.43.45.3"
    hostnames:
      - prod.auth.crivo.local
      - prod.be.crivo.local
      - prod.fe.crivo.local

# TEMP: idem develop, até a imagem prod sair com prisma.config.ts.
initContainers: []
