app:
  environment: prod

image:
  # NOTA: usando tag 'develop' enquanto CI não publica tag 'main'.
  # Em prod-prod real: usar versão semântica (v1.2.3) ou SHA.
  tag: "main-dfaa068ee4e0e705946dc3df9eb5f522fc7628c8"

ingress:
  host: prod.fe.crivo.local

env:
  NODE_ENV: production
  BETTER_AUTH_URL: http://prod.fe.crivo.local
  # API_URL e INTERNAL_API_URL: server-side chama o BE direto pelo Service.
  API_URL: http://crivo-be.crivo-prod.svc.cluster.local:3000
  INTERNAL_API_URL: http://crivo-be.crivo-prod.svc.cluster.local:3000
  # NEXT_PUBLIC_API_URL: browser passa por Kong.
  NEXT_PUBLIC_API_URL: http://prod.api.crivo.local/api
  NEXT_PUBLIC_KEYCLOAK_URL: http://prod.auth.crivo.local
  NEXT_PUBLIC_KEYCLOAK_ISSUER: http://prod.auth.crivo.local/realms/crivo
  AUTH_KEYCLOAK_ISSUER: http://prod.auth.crivo.local/realms/crivo

podDisruptionBudget:
  enabled: true
  minAvailable: 1

hostAliases:
  - ip: "10.43.45.3"
    hostnames:
      - prod.auth.crivo.local
      - prod.be.crivo.local
      - prod.fe.crivo.local
      - prod.api.crivo.local
