app:
  environment: develop

image:
  tag: develop

ingress:
  host: develop.fe.crivo.local

env:
  NODE_ENV: development
  BETTER_AUTH_URL: http://develop.fe.crivo.local
  # API_URL: chamadas server-side do Next vão direto no Service interno do BE.
  API_URL: http://crivo-be.crivo-develop.svc.cluster.local:3000
  # NEXT_PUBLIC_API_URL: chamadas do browser passam pelo Kong (API gateway).
  # Kong adiciona /api prefix nas rotas; ver kong.yml.
  NEXT_PUBLIC_API_URL: http://develop.api.crivo.local/api
  NEXT_PUBLIC_KEYCLOAK_URL: http://develop.auth.crivo.local

hostAliases:
  - ip: "10.43.45.3"
    hostnames:
      - develop.auth.crivo.local
      - develop.be.crivo.local
      - develop.fe.crivo.local
      - develop.api.crivo.local
