app:
  environment: develop

ingress:
  host: develop.api.crivo.local

hostAliases:
  - ip: "10.43.45.3"
    hostnames:
      - develop.auth.crivo.local
      - develop.be.crivo.local
      - develop.fe.crivo.local
      - develop.api.crivo.local
