app:
  environment: prod

ingress:
  host: prod.api.crivo.local

podDisruptionBudget:
  enabled: true
  minAvailable: 1

hostAliases:
  - ip: "10.43.45.3"
    hostnames:
      - prod.auth.crivo.local
      - prod.be.crivo.local
      - prod.fe.crivo.local
      - prod.api.crivo.local
