# Values for Development environment
replicaCount: 1

image:
  repository: ghcr.io/geraldobl58/crivo-be
  tag: "develop-dceb65cf88fc857e162f58c1b2bc387a98a8848e"
  pullPolicy: Always

imagePullSecrets:
  - name: ghcr-secret

ingress:
  enabled: true
  className: "nginx"
  annotations:
  hosts:
    - host: develop-be.devops.local
      paths:
        - path: /
          pathType: Prefix

resources:
  limits:
    cpu: 200m
    memory: 256Mi
  requests:
    cpu: 10m
    memory: 64Mi

autoscaling:
  enabled: false

env:
  NODE_ENV: development
  PORT: "3000"
  LOG_LEVEL: debug
  SWAGGER_ENABLED: "true"
  METRICS_ENABLED: "true"
  KEYCLOAK_URL: "http://develop-auth.devops.local"
  KEYCLOAK_INTERNAL_URL: "http://crivo-auth-develop:8080"
  KEYCLOAK_REALM: devops

podDisruptionBudget:
  enabled: false

podAnnotations:
  app.kubernetes.io/commit: "dceb65c"

metrics:
  enabled: false
  path: /metrics
  serviceMonitor:
    enabled: false

# Kubernetes Secret com as credenciais do Cloudinary.
# Criar o secret antes de implantar:
#   kubectl create secret generic crivo-be-cloudinary -n crivo-develop \
#     --from-literal=CLOUDINARY_CLOUD_NAME=xxx \
#     --from-literal=CLOUDINARY_API_KEY=xxx \
#     --from-literal=CLOUDINARY_API_SECRET=xxx \
#     --from-literal=CLOUDINARY_FOLDER=devops
envFrom:
  - secretRef: crivo-be-cloudinary
